version: '3'

vars:
  COMMIT_MESSAGE: changed from intel to ARM lambda
  # COMMIT_MESSAGE: updated to 1.125.0

tasks:
  default:
    cmds:
      - git add .
      - git commit -m "{{.COMMIT_MESSAGE}}"
      - git push origin master